
import React, { createContext, useContext, useState, ReactNode } from 'react';

export type Language = 'VN' | 'JP';

interface LanguageContextType {
    language: Language;
    setLanguage: (lang: Language) => void;
    t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const translations: Record<Language, Record<string, string>> = {
    VN: {
        "search": "Tìm kiếm",
        "signIn": "Đăng nhập",
        "date_format": "dd/MM/yyyy", // We handle date formatting separately usually, but good to have a key
        "readTime": "phút đọc",
        "latestNews": "Tin mới nhất",
        "editorsPick": "Lựa chọn của biên tập viên",
        "recommended": "Đề xuất cho bạn",
        "viewMore": "Xem thêm",
        "copyright": "Bản quyền thuộc về Betonabi",
        "category_Latest": "Mới nhất",
        "category_MostRead": "Đọc nhiều",
        "category_Business": "Kinh doanh",
        "category_Politics": "Chính trị",
        "category_Society": "Xã hội",
        "category_Sports": "Thể thao",
        "category_Culture": "Văn hóa",
        "category_Travel": "Du lịch",
        "category_Health": "Sức khỏe",
        "category_Education": "Giáo dục",
        "category_Life": "Đời sống",
        "category_TravelCulture": "Du lịch - Văn hóa",
        "category_Longform": "Longform",
        "home": "Trang chủ",
        "home_title": "Betonabi",
        "hot_topics": "Chủ đề nổi bật",
        "follow_us": "Theo dõi chúng tôi",
        "most_viewed": "Xem nhiều nhất",
        "footer_about": "Trang tin tức uy tín hàng đầu Việt Nam. Cập nhật tin tức mới nhất 24/7.",
        "footer_categories": "Chuyên mục",
        "footer_services": "Dịch vụ",
        "footer_subscribe": "Đăng ký",
        "footer_ads": "Quảng cáo",
        "footer_contact": "Liên hệ",
        "footer_terms": "Điều khoản sử dụng",
        "footer_get_latest": "Nhận tin mới nhất",
        "footer_subscribe_text": "Đăng ký để nhận tin tức nóng hổi mỗi ngày.",
        "footer_email_placeholder": "Email của bạn",
        "footer_rights": "© 2025 Betonabi. Bảo lưu mọi quyền.",
        "footer_about_link": "Về Betonabi",
        "footer_follow": "Theo dõi Betonabi",
        "footer_newsletter_title": "Đừng bỏ lỡ tin tức quan trọng!",
        "footer_newsletter_summary": "Nhận tóm tắt tin tức hấp dẫn 24 giờ qua trên Betonabi",
        "footer_subscribe_btn": "Đăng ký",
        "footer_content_manager": "Chịu trách nhiệm quản lý nội dung:",
        "footer_manager_name": "Nguyễn Thị Minh Chi",
        "footer_copyright_text": "© Toàn bộ bản quyền thuộc Betonabi",
        "header_subscribe": "Theo dõi",
        "header_register": "Đăng ký",
        "footer_built": "Được xây dựng với ❤️ tại Việt Nam",
        "contact_title": "Liên hệ với Betonabi",
        "contact_intro": "Ban có thể đặt câu hỏi về trang web Betonabi.",
        "contact_intro_note_start": "Vui lòng điền vào biểu mẫu dưới đây. (",
        "contact_intro_note_end": " trường bắt buộc)",
        "contact_required": "trường bắt buộc",
        "contact_fullname": "Họ và Tên",
        "contact_fullname_placeholder": "Nhập họ và tên của bạn",
        "contact_company": "Tên công ty/tổ chức",
        "contact_company_placeholder": "Nhập công ty hoặc tổ chức",
        "contact_company_warning": "Nếu không cung cấp tên công ty hoặc tổ chức của bạn, đơn đăng ký sẽ bị từ chối.",
        "contact_department": "Phòng ban",
        "contact_department_placeholder": "Nhập tên phòng ban (không bắt buộc)",
        "contact_email": "Địa chỉ email",
        "contact_email_placeholder": "Nhập địa chỉ email của bạn",
        "contact_email_warning": "* Bắt buộc nhập địa chỉ email của cá nhân hoặc tổ chức của bạn.",
        "contact_email_warning2": "* Các địa chỉ email miễn phí KHÔNG được chấp nhận.",
        "contact_phone": "Số điện thoại",
        "contact_phone_placeholder": "Nhập số điện thoại (không bắt buộc)",
        "contact_message": "Tin nhắn",
        "contact_message_placeholder": "Nhập tin nhắn của bạn...",
        "contact_submit": "Gửi",
        "about_title": "Về Betonabi",
        "about_intro": "Betonabi cung cấp tin tức chuyên sâu về Việt Nam trong nhiều lĩnh vực như văn hóa, kinh doanh, đời sống, du lịch, sức khỏe, với góc nhìn trung thực, khách quan. Ngoài ra, thông qua hợp tác với các đối tác, chúng tôi mang đến các nội dung phong phú về đất nước và con người Việt Nam với những hình ảnh, video chân thực.",
        "about_mission": "Với hai phiên bản gồm tiếng Việt và tiếng Nhật, Betonabi hi vọng sẽ được độc giả đón đọc và coi là nguồn tin đáng tin cậy về Việt Nam.",
        "about_cta": "Nếu bạn quan tâm, vui lòng liên hệ với chúng tôi.",
        "about_contact_button": "Liên hệ",
        "nav_about": "Về chúng tôi",
        "nav_contact": "Liên hệ với chúng tôi",
        "save": "Lưu",
        "share": "Chia sẻ",
        "tags": "Tags",
        "opinions": "Ý kiến",
        "share_opinion": "Chia sẻ ý kiến của bạn...",
        "login_title": "Đăng nhập/Tạo tài khoản",
        "email_label": "Email",
        "email_placeholder": "Nhập email của bạn",
        "continue": "Tiếp tục",
        "or": "Hoặc",
        "login_terms": "Tiếp tục là đồng ý với điều khoản sử dụng và chính sách bảo mật của Betonabi. Tài khoản của bạn được reCAPTCHA bảo vệ.",
        "login_google": "Đăng nhập với Google",
        "login_apple": "Đăng nhập với Apple",
        "login_as_admin": "Đăng nhập Admin",
        "login_as_guest": "Đăng nhập Khách"
    },
    JP: {
        "search": "検索",
        "signIn": "ログイン",
        "date_format": "yyyy/MM/dd",
        "readTime": "分",
        "latestNews": "最新ニュース",
        "editorsPick": "編集長のおすすめ",
        "recommended": "おすすめ",
        "viewMore": "もっと見る",
        "copyright": "© Betonabi",
        "category_Latest": "新着",
        "category_MostRead": "ランキング",
        "category_Business": "ビジネス",
        "category_Politics": "政治",
        "category_Society": "社会",
        "category_Sports": "スポーツ",
        "category_Culture": "文化",
        "category_Travel": "旅行",
        "category_Health": "健康",
        "category_Education": "教育",
        "category_Life": "ライフ",
        "category_TravelCulture": "旅行・文化",
        "category_Longform": "特集",
        "home": "トップ",
        "home_title": "ミ・チ・ライター",
        "hot_topics": "注目ワード",
        "follow_us": "フォローする",
        "most_viewed": "人気の記事",
        "footer_about": "ベトナム有数の信頼できるニュースサイト。最新ニュースを24時間年中無休で更新。",
        "footer_categories": "カテゴリー",
        "footer_services": "サービス",
        "footer_subscribe": "登録",
        "footer_ads": "広告",
        "footer_contact": "お問い合わせ",
        "footer_terms": "利用規約",
        "footer_get_latest": "最新ニュースを受け取る",
        "footer_subscribe_text": "毎日最新のニュースを受け取るために登録してください。",
        "footer_email_placeholder": "メールアドレス",
        "footer_rights": "© 2025 Betonabi. 全著作権所有。",
        "footer_about_link": "Betonabiについて",
        "footer_follow": "Betonabiをフォロー",
        "footer_newsletter_title": "重要ニュースをお見逃しなく！",
        "footer_newsletter_summary": "Betonabiの過去24時間の注目ニュースをまとめ読み",
        "footer_subscribe_btn": "登録する",
        "footer_content_manager": "コンテンツ運営責任者：",
        "footer_manager_name": "Nguyễn Thị Minh Chi（グエン・ティ・ミン・チー） ",
        "footer_copyright_text": "© Betonabi. All Rights Reserved.",
        "header_subscribe": "購読",
        "header_register": "登録",
        "footer_built": "ベトナムで❤️を込めて作られました",
        "contact_title": "Betonabiへの お問い合わせ",
        "contact_intro": "Betonabiに関するお問い合わせは、以下のフォームよりお願いいたします。",
        "contact_intro_note_start": "（",
        "contact_intro_note_end": " は必須項目です）",
        "contact_required": "必須項目",
        "contact_fullname": "氏名",
        "contact_fullname_placeholder": "氏名をご入力ください。",
        "contact_company": "会社名・団体名",
        "contact_company_placeholder": "会社名または団体名をご入力ください。",
        "contact_company_warning": "会社名・団体名のご記入がない場合、対応いたしかねますのでご了承ください。",
        "contact_department": "部署名",
        "contact_department_placeholder": "部署名をご入力ください（任意）",
        "contact_email": "メールアドレス",
        "contact_email_placeholder": "メールアドレスをご入力ください。",
        "contact_email_warning": "企業または組織のメールアドレスをご入力ください。",
        "contact_email_warning2": "フリーメールアドレスはご利用いただけません。",
        "contact_phone": "電話番号",
        "contact_phone_placeholder": "電話番号をご入力ください（任意）",
        "contact_message": "お問い合わせ内容",
        "contact_message_placeholder": "お問い合わせ内容をご入力ください。",
        "contact_submit": "送信する",
        "about_title": "Betonabiについて",
        "about_intro": "Betonabiは、文化、ビジネス、ライフ、旅行、健康といった幅広い分野において、客観的かつ誠実な視点からベトナムに関する深掘りニュースを提供しています。また、各種パートナーとの連携を通じて、リアルな写真や動画を交えながら、ベトナムという国や人々に関する魅力的なコンテンツをお届けします。",
        "about_mission": "ベトナム語と日本語の2カ国語で展開するBetonabiが、多くの読者の皆様にご愛読いただき、ベトナムに関する信頼できる情報源としてお役に立てることを願っています。",
        "about_cta": "ご興味のある方は、どうぞお気軽にお問い合わせください。",
        "about_contact_button": "お問い合わせ",
        "nav_about": "私たちについて",
        "nav_contact": "お問い合わせ",
        "login_as_admin": "管理者としてログイン",
        "login_as_guest": "ゲストとしてログイン",
        "save": "保存して後で読む",
        "share": "シェア",
        "tags": "関連ワード",
        "opinions": "コメント",
        "share_opinion": "ご意見をお聞かせください",
        "login_title": "ログイン / 新規登録",
        "email_label": "メールアドレス",
        "email_placeholder": "メールアドレスをご入力ください。",
        "continue": "次へ",
        "or": "または",
        "login_terms": "続行することで、Betonabiの利用規約およびプライバシーポリシーに同意したものとみなされます。このサイトはreCAPTCHAによって保護されています。",
        "login_google": "Googleでログイン",
        "login_apple": "Appleでログイン"
    }
};

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
    const [language, setLanguage] = useState<Language>('VN');

    const t = (key: string) => {
        return translations[language][key] || key;
    };

    return (
        <LanguageContext.Provider value={{ language, setLanguage, t }}>
            {children}
        </LanguageContext.Provider>
    );
};

export const useLanguage = () => {
    const context = useContext(LanguageContext);
    if (context === undefined) {
        throw new Error('useLanguage must be used within a LanguageProvider');
    }
    return context;
};
